'use strict';
const services=[['ponto','◷','Ponto eletrônico','Ajustes e orientações'],['desempenho','↗','Desenvolvimento','Conversas e objetivos'],['pagamento','▤','Folha de pagamento','Documentos e dúvidas'],['reembolso','◇','Reembolso','Organize sua solicitação'],['treinamento','▣','Treinamentos','Aprenda no seu ritmo'],['suporte','⌘','Suporte de TI','Acessos e equipamentos']];
const benefits=[['saude','♡','Plano de saúde'],['odonto','♧','Plano odontológico'],['ferias','☀','Solicitar férias'],['convenios','☆','Convênios'],['comunicacao','▤','Comunicação'],['ouvidoria','♧','Ouvidoria']];
const content={
perfil:['Seu espaço','Ana Lima','Perfil demonstrativo de colaboradora da área de Operações.','Seus pontos de apoio',['Pessoas & Cultura: benefícios e jornada.','Tecnologia: acessos e equipamentos.','Liderança: prioridades e desenvolvimento.']],
cultura:['Cultura','O próximo capítulo se constrói em equipe','O programa Conexões cria oportunidades de troca entre áreas. A proposta desta edição é documentar melhor as decisões e simplificar a rotina.','Como participar',['Observe um atrito recorrente no seu dia a dia.','Converse com quem participa do processo antes de propor mudanças.','Registre uma ideia com benefício esperado e um primeiro passo viável.']],
ponto:['Meu dia a dia','Ponto eletrônico','Consulte suas marcações no sistema oficial e reúna as informações antes de pedir um ajuste.','Antes de solicitar',['Informe a data e o horário que precisam de revisão.','Descreva o motivo de forma objetiva, sem incluir dados sensíveis.','Combine com a liderança a validação do registro.']],
desempenho:['Desenvolvimento','Conversas que ajudam a evoluir','Use os encontros de acompanhamento para alinhar expectativas, reconhecer avanços e pedir apoio.','Roteiro de conversa',['Revise os objetivos e reúna exemplos de entregas.','Identifique um aprendizado e uma dificuldade do período.','Defina uma ação de desenvolvimento com prazo de revisão.']],
pagamento:['Pessoas & Cultura','Folha de pagamento','Esta central demonstra como organizar o acesso a documentos e encaminhar dúvidas para a equipe responsável.','Para uma consulta mais rápida',['Localize a competência do documento que deseja consultar.','Confira se sua dúvida é sobre rubrica, benefício ou informação cadastral.','Utilize o canal oficial restrito para documentos financeiros; não compartilhe valores em espaços abertos.']],
reembolso:['Serviços','Organize seu reembolso','Um pedido bem documentado facilita a análise. As regras e os prazos devem ser confirmados na política oficial da empresa.','Checklist de preparação',['Identifique a finalidade da despesa e o centro de custo.','Reúna comprovantes legíveis e a aprovação necessária.','Confira os dados antes de enviar pelo sistema autorizado.']],
treinamento:['Academia Conecta','Aprendizado no seu ritmo','Trilhas ilustrativas para apoiar a colaboração e a organização do trabalho.','Trilhas em destaque',['Comunicação clara: pedidos, contexto e combinados — 35 minutos.','Organização de arquivos: nomes, versões e permissões — 25 minutos.','Colaboração entre áreas: passagem de atividades — 40 minutos.']],
saude:['Benefícios','Plano de saúde','Encontre o caminho para consultar a rede, verificar sua identificação e tirar dúvidas de cadastro.','Onde começar',['Consulte a rede atualizada no canal oficial da operadora.','Para inclusão ou alteração cadastral, procure Pessoas & Cultura.','Documentos pessoais devem ser encaminhados apenas pelo canal seguro indicado pela equipe.']],
odonto:['Benefícios','Plano odontológico','Central demonstrativa para orientar o acesso ao benefício e aos canais de atendimento.','Informações úteis',['Confirme sua situação cadastral com Pessoas & Cultura.','Consulte a rede credenciada e a cobertura diretamente com a operadora.','Anote o protocolo quando precisar acompanhar um atendimento.']],
convenios:['Benefícios','Convênios e parcerias','Explore categorias de parcerias que podem fazer parte de um programa de benefícios.','Categorias ilustrativas',['Educação: idiomas e formação continuada.','Bem-estar: atividades e experiências para a rotina.','Cultura: oportunidades para aproveitar fora do trabalho.']],
comunicacao:['Comunicação interna','Sua informação no canal certo','Ajude a equipe a dar visibilidade ao que é relevante. Prepare um briefing antes de solicitar uma divulgação.','O que incluir',['O que aconteceu e por que importa para as pessoas.','Público, data, responsável e ação esperada.','Materiais autorizados para divulgação, com contexto e créditos.']],
ouvidoria:['Escuta','Um canal de confiança','Este protótipo apresenta apenas uma orientação de navegação. Não registre relatos sensíveis aqui.','Como buscar apoio',['Localize o canal oficial de ouvidoria ou integridade da empresa.','Confira as condições de confidencialidade antes de compartilhar informações.','Guarde o protocolo para acompanhamento no ambiente autorizado.']],
integracao:['Guia de integração','Seus primeiros passos','Uma chegada acolhedora combina contexto, acesso às ferramentas e pessoas disponíveis para ajudar.','Roteiro da primeira semana',['Primeiro dia: conheça sua liderança e os canais da equipe.','Ferramentas: confirme acessos e registre necessidades com TI.','Rotina: entenda prioridades, rituais e entregas da área.','Ao final da semana: reserve uma conversa para dúvidas e próximos passos.']],
processos:['Biblioteca colaborativa','Processos sem complicação','Registros curtos e claros ajudam outras pessoas a continuar uma atividade sem depender de uma única pessoa.','Modelo de passagem de atividade',['Contexto: qual problema estamos resolvendo?','Responsável e prazo: quem continua e até quando?','Materiais: onde estão os arquivos e a versão atual?','Critério de conclusão: como saberemos que está pronto?']],
seguranca:['Boas práticas','Segurança no cotidiano','Pequenos cuidados ajudam a proteger as informações compartilhadas no trabalho.','Lembretes para a rotina',['Confira remetente e endereço antes de abrir links inesperados.','Nunca compartilhe senhas ou códigos de autenticação.','Revise permissões antes de distribuir arquivos.','Se suspeitar de um incidente, procure o suporte oficial e preserve o contexto.']]
};
const quick=document.querySelector('#quick-grid');services.forEach(([id,icon,title,sub])=>{const b=document.createElement('button');b.dataset.open=id;b.innerHTML=`<span class="quick-icon" aria-hidden="true">${icon}</span><span><b>${title}</b><small>${sub}</small></span>`;quick.append(b)});
benefits.forEach(([id,icon,title])=>{const b=document.createElement('button');b.dataset.open=id;b.innerHTML=`<span aria-hidden="true">${icon}</span>${title}`;document.querySelector('#employee-links').append(b)});
const dialog=document.querySelector('#detail'),body=document.querySelector('#dialog-content');let trigger;
function open(title,category){trigger=document.activeElement;document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-category').textContent=category;body.replaceChildren();dialog.showModal();document.body.style.overflow='hidden'}
function close(){dialog.close()};dialog.querySelector('.close').onclick=close;dialog.addEventListener('close',()=>{document.body.style.overflow='';trigger?.focus()});dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()});
function showContent(id){if(['suporte','ferias','ideias'].includes(id)){showForm(id);return}const c=content[id];if(!c)return;open(c[1],c[0]);const p=document.createElement('p');p.textContent=c[2];const h=document.createElement('h3');h.textContent=c[3];const ul=document.createElement('ul');c[4].forEach(t=>{const li=document.createElement('li');li.textContent=t;ul.append(li)});body.append(p,h,ul);const note=document.createElement('p');note.className='dialog-note';note.textContent='Conteúdo ilustrativo. Confirme políticas, disponibilidade e canais no ambiente oficial da empresa.';body.append(note)}
function showForm(type){const config={suporte:['Central de ajuda','Descreva o que precisa, sem incluir senhas ou dados confidenciais.'],ferias:['Planejar férias','Experimente informar um período. A simulação não reserva datas nem substitui a aprovação da liderança.'],ideias:['Compartilhar uma ideia','Conte qual rotina pode melhorar e como você imagina o primeiro passo.']}[type];open(config[0],'SOLICITAÇÃO DEMONSTRATIVA');body.innerHTML=`<p>${config[1]}</p><form class="demo-form"><label>Seu nome<input name="name" value="Ana Lima" required maxlength="80"></label>${type==='ferias'?'<label>Início do período<input name="start" type="date" required></label><label>Fim do período<input name="end" type="date" required></label>':'<label>Área<select name="area"><option>Tecnologia</option><option>Pessoas & Cultura</option><option>Operações</option><option>Comunicação</option></select></label><label>Conte um pouco mais<textarea name="message" rows="4" minlength="10" maxlength="1200" required></textarea></label>'}<p class="dialog-note">Nada será enviado ou armazenado. Use somente informações fictícias.</p><button class="button" type="submit">Simular solicitação ↗</button></form>`;const form=body.querySelector('form');if(type==='ferias'){const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;form.elements.start.min=today;form.elements.end.min=today;form.elements.start.oninput=()=>form.elements.end.min=form.elements.start.value||today}form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;body.innerHTML='<div class="success" role="status"><h3>Simulação concluída</h3><p>Seu pedido foi demonstrado com sucesso. Nenhuma solicitação real foi criada e nenhum dado foi enviado ou armazenado.</p></div>'}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-open]');if(el)showContent(el.dataset.open)});
document.querySelector('#service-search').addEventListener('input',e=>{const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const q=norm(e.target.value);let count=0;quick.querySelectorAll('button').forEach(b=>{b.hidden=!norm(b.textContent).includes(q);if(!b.hidden)count++});document.querySelector('#search-empty').hidden=count>0});
const news=[['Cultura','Uma ideia simples pode mudar uma rotina.','Conheça o programa Conexões e veja como estruturar uma proposta de melhoria.','assets/team.webp','cultura'],['Serviços','Seu pedido de suporte, com mais contexto.','O que informar para facilitar o entendimento e reduzir a troca de mensagens.','assets/office.webp','suporte'],['Cultura','Conhecimento bom é conhecimento compartilhado.','Descubra os roteiros de integração e ajude a acolher quem está chegando.','assets/conference.webp','integracao']];
news.forEach(([category,title,desc,img,id])=>{const a=document.createElement('article');a.className='news-card';a.dataset.category=category;a.innerHTML=`<img src="${img}" alt="" loading="lazy"><div><small>${category.toUpperCase()} · 15 SET</small><h3>${title}</h3><p>${desc}</p><button class="text-button" data-open="${id}">Ler conteúdo ↗</button></div>`;document.querySelector('#news-grid').append(a)});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});document.querySelectorAll('.news-card').forEach(x=>x.hidden=b.dataset.filter!=='Todas'&&x.dataset.category!==b.dataset.filter)});
document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{open(b.dataset.event,'AGENDA CONECTA');body.innerHTML='<p>Encontro demonstrativo com apresentação de 20 minutos, conversa entre participantes e espaço para perguntas.</p><h3>O que você vai encontrar</h3><ul><li>Um exemplo prático para discutir em equipe.</li><li>Troca de experiências e aprendizados.</li><li>Um pequeno roteiro para experimentar depois.</li></ul><button class="button" id="join-event">Simular minha inscrição ↗</button>';body.querySelector('button').onclick=()=>{body.innerHTML='<div class="success" role="status"><h3>Participação simulada!</h3><p>Nenhum convite foi enviado e nenhum evento foi adicionado à sua agenda.</p></div>'}});
let toastTimer;document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{const toast=document.querySelector('.toast');toast.textContent=`Um carinho para ${b.dataset.person}! Interação demonstrativa, sem envio de mensagem.`;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,5000)});
const menu=document.querySelector('.menu'),nav=document.querySelector('#nav');menu.onclick=()=>{const active=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(active))};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
const reduced=matchMedia('(prefers-reduced-motion:reduce)');const targets=document.querySelectorAll('.employee-panel,.spotlight-grid,.knowledge-grid,.agenda-grid,.people-grid,.news-grid');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});if(!reduced.matches)targets.forEach(el=>{el.classList.add('reveal');observer.observe(el)});
