'use strict';
const paths={medal:'M18 3a10 10 0 1 0 0 20 10 10 0 0 0 0-20 M18 7a6 6 0 1 0 0 12 6 6 0 0 0 0-12 M11 21 6 33l9-3 3 4 3-4 9 3-5-12',person:'M18 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M4 33v-4c0-12 28-12 28 0v4Z',target:'M18 6a12 12 0 1 0 0 24 12 12 0 0 0 0-24 M18 12a6 6 0 1 0 0 12 6 6 0 0 0 0-12 M18 1v8 M18 27v8 M1 18h8 M27 18h8',leaf:'M7 29C-1 8 18 4 31 3c0 19-6 30-24 26Z M4 33 26 9 M12 24v-9 M19 17h9',molecule:'M6 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6 M28 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6 M19 16a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M7 28a3 3 0 1 0 0 6 3 3 0 0 0 0-6 M30 27a3 3 0 1 0 0 6 3 3 0 0 0 0-6 M9 11l7 6 M25 8l-4 8 M16 23l-6 6 M23 23l5 5',cycle:'M30 11a14 14 0 1 0 2 13 M30 3v9h-9'};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=`<svg class="icon" viewBox="0 0 36 36" aria-hidden="true"><path d="${paths[el.dataset.icon]}"/></svg>`);
const specialties=[['Nutrição para performance','Um acompanhamento que começa por conhecer a sua rotina, sua relação com a alimentação e seus objetivos no esporte. As próximas etapas são discutidas de forma individual na avaliação.'],['Saúde hormonal','Um espaço para conversar sobre seu histórico, suas dúvidas e seu momento de vida. A proposta é compreender o contexto de cada pessoa antes de definir qualquer conduta.'],['Recuperação e longevidade','Conhecer sua trajetória esportiva e suas prioridades ajuda a contextualizar o cuidado. O acompanhamento abre espaço para revisar objetivos e conversar sobre as mudanças na rotina.']];
const articles=[['O começo de um acompanhamento individual.','O primeiro encontro é dedicado à escuta. Você pode contar sua história, sua experiência no esporte e o que deseja discutir. O atendimento parte desse contexto para conversar sobre os próximos passos.'],['Cada pessoa tem uma relação com o esporte.','Há diferentes trajetórias: quem está começando, quem encontrou uma prática para a rotina e quem vive o esporte de forma intensa. Conhecer essa relação é parte importante da conversa com a profissional.'],['Um espaço para perguntas e acompanhamento.','Comunicação clara é parte da proposta de atendimento. Há espaço para perguntas, para revisitar objetivos e para conversar sobre as mudanças da sua rotina. Este conteúdo apresenta o conceito do consultório, sem orientação clínica individual.']];
const nav=document.querySelector('#menu'),menuButton=document.querySelector('.menu-toggle');
function closeMenu(){nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Abrir menu');}
menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const booking=document.querySelector('#booking'),details=document.querySelector('#details'),form=document.querySelector('#booking-form'),result=document.querySelector('#booking-result');
const triggers=new WeakMap();let selectedGoal;
function openDialog(dialog,trigger=document.activeElement){triggers.set(dialog,trigger);dialog.showModal();document.body.classList.add('modal-open');}
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelector('[data-close]').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]')){document.body.classList.remove('modal-open');triggers.get(dialog)?.focus();}});});
function today(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;}
form.elements.goal.required=true;
function openBooking(goal){let trigger=document.activeElement;if(details.open){trigger=triggers.get(details);details.close();}form.reset();form.hidden=false;result.hidden=true;form.elements.date.min=today();if(goal)form.elements.goal.value=goal;openDialog(booking,trigger);}
document.querySelectorAll('[data-book]').forEach(button=>button.addEventListener('click',()=>openBooking()));
function showDetails(title,text,goal,category){selectedGoal=goal;document.querySelector('#detail-title').textContent=title;document.querySelector('#detail-text').textContent=text;document.querySelector('#detail-category').textContent=category;openDialog(details);}
document.querySelectorAll('[data-specialty]').forEach(button=>button.addEventListener('click',()=>{const item=specialties[Number(button.dataset.specialty)];showDetails(item[0],item[1],item[0],'Áreas de atuação');}));
document.querySelectorAll('[data-article]').forEach(button=>button.addEventListener('click',()=>{const item=articles[Number(button.dataset.article)];showDetails(item[0],item[1],'Conhecer o acompanhamento','Conteúdos');}));
document.querySelector('#detail-book').addEventListener('click',()=>openBooking(selectedGoal));
form.addEventListener('submit',e=>{e.preventDefault();form.elements.date.min=today();if(!form.reportValidity())return;const data=new FormData(form);const date=new Date(`${data.get('date')}T12:00:00`).toLocaleDateString('pt-BR');result.textContent=`Simulação concluída, ${data.get('name')}! Sua solicitação de avaliação ${data.get('format').toLowerCase()} para ${data.get('goal').toLowerCase()}, em ${date}, foi demonstrada com sucesso. Nenhuma consulta foi marcada e nenhum dado foi enviado ou armazenado.`;form.hidden=true;result.hidden=false;});
const tabs=[...document.querySelectorAll('[role="tab"]')];
function selectTab(tab){tabs.forEach(item=>{const active=item===tab;item.setAttribute('aria-selected',String(active));item.tabIndex=active?0:-1;document.getElementById(item.getAttribute('aria-controls')).hidden=!active;});}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(index+1)%tabs.length;if(e.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();selectTab(tabs[next]);tabs[next].focus();}});});
const reduced=matchMedia('(prefers-reduced-motion: reduce)');const revealTargets=document.querySelectorAll('.specialty-card,.method-grid article,.about-grid,.results-grid,.article-grid article,.contact-inner');let revealObserver;
function setupReveals(){revealObserver?.disconnect();if(reduced.matches){revealTargets.forEach(el=>el.classList.add('visible'));return;}revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target);}}),{threshold:.08});revealTargets.forEach(el=>{el.classList.add('reveal');revealObserver.observe(el);});}
setupReveals();reduced.addEventListener('change',setupReveals);
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)nav.querySelectorAll('a').forEach(a=>{const active=a.hash===`#${entry.target.id}`;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}),{rootMargin:'-5% 0px -60% 0px',threshold:0});
['inicio','especialidades','metodo','resultados','conteudos','contato'].forEach(id=>sectionObserver.observe(document.getElementById(id)));
const contactForm=document.querySelector('#contact-form');
contactForm.addEventListener('submit',event=>{event.preventDefault();if(!contactForm.reportValidity())return;const data=new FormData(contactForm);document.querySelector('#contact-summary').value=`Nome: ${data.get('name')}\nE-mail: ${data.get('email')}\nAcompanhamento: ${data.get('goal')}\n\n${data.get('message')}`;document.querySelector('#contact-result').hidden=false;document.querySelector('#contact-result').scrollIntoView({block:'nearest',behavior:reduced.matches?'auto':'smooth'});});
document.querySelector('#copy-message').addEventListener('click',async()=>{const summary=document.querySelector('#contact-summary');try{await navigator.clipboard.writeText(summary.value);document.querySelector('#copy-status').textContent='Mensagem copiada.';}catch{summary.focus();summary.select();document.querySelector('#copy-status').textContent='Selecione e copie o resumo acima.';}});
document.querySelector('#download-message').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([document.querySelector('#contact-summary').value],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='mensagem-marina-azevedo.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
